title: site title
description: meta description
social_fb_slug: fakebook
social_ig_slug: instascam
social_email: user@email.com
theme-color: "#317EFB"
hours: Tue-Sun 5pm&ndash;9pm <br> Mon closed <br>
